In [1]:
import numpy as np
import pandas as pd

In [5]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [6]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [9]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [10]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [12]:
# 1. Extra Year
date['date_year'] = date['date'].dt.year # dt - means date 
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [16]:
# Extra Month
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no  date_day
0 2019-12-10        5628       25       3       2019             12        10
1 2018-08-15        3646       14     157       2018              8        15
2 2018-10-23        1859       25       1       2018             10        23
3 2019-08-17        7292       25       1       2019              8        17
4 2019-01-06        4344       25       3       2019              1         6

In [15]:
# Extract Days
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_month_no  date_day
0 2019-12-10        5628       25       3       2019             12        10
1 2018-08-15        3646       14     157       2018              8        15
2 2018-10-23        1859       25       1       2018             10        23
3 2019-08-17        7292       25       1       2019              8        17
4 2019-01-06        4344       25       3       2019              1         6

In [17]:
# days of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [18]:
# day of the week name 
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id', 'city_id', 'orders']).head()

        date  date_year  date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019             12        10         1       Tuesday
1 2018-08-15       2018              8        15         2     Wednesday
2 2018-10-23       2018             10        23         1       Tuesday
3 2019-08-17       2019              8        17         5      Saturday
4 2019-01-06       2019              1         6         6        Sunday

In [19]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,10,1,Tuesday,0
1,2018-08-15,2018,8,15,2,Wednesday,0
2,2018-10-23,2018,10,23,1,Tuesday,0
3,2019-08-17,2019,8,17,5,Saturday,1
4,2019-01-06,2019,1,6,6,Sunday,1

In [20]:
# Extract week of the year

date['date_week'] = date['date'].dt.week

date.drop(columns=['product_id','city_id','orders']).head()

AttributeError: 'DatetimeProperties' object has no attribute 'week'